tspgw:
  jms-timeout: ${internal.timeout.ms}
  callback-response-queue-name: callbackQueue-${spring.application.instance_id}
  long-jms-timeout: ${internal.timeout.ms}
#----------------------------------------------------------------------------
spring.jmx.enabled: true
spring.cloud.config.enabled: false

# Settings for asynchronous calls management.
# This settings were tested with:
# - number of asynchronous requests: 3000
# - number of asynchronous requests per second: 60
async.notification:
  thread-pool:
    core-pool-size: 32
    max-pool-size: 64
    queue-capacity: 64 # As a rule of thumb, the queueCapacity should be at least as big as the batchSize
  retry:
    initial-retries: 5
    retry-after: 30s
    timeout: 30s
    load-retry-delay: 1s # delay before reloading a new batch of notification sequences if last load returned no sequences
    parallel-sequences: 16 # max number of notification sequences processing at the same time
  delete:
    fixed-delay: 10m
    initial-delay: 20m
    delete-after: 10m
  alarm-trigger:
    new-status:
      alarm-trigger-count: 500
      avg-age: 900s
      avg-age-over: 5m
      max-age: 1200s
      max-age-over: 10m
    sent-status:
      sent-during-last: 1800s  # value << cleanup period

logging:
  # to enable Spring logfile actuator (also needs endpoint config)
  file: ${app.logdir}/${spring.application.name}-debug.log
  level:
    ROOT: INFO
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: ERROR
